Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "ansible-homework"

  config.vm.define "ans" do |ans|
    ans.vm.network :private_network, ip: "192.168.98.100"
  end

  config.vm.synced_folder "./data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "1024"
  end
  
 # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
 #    apt-get install -y python3
 # SHELL
  
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "main/playbook.yml"
  end
end
