# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
  
    config.vm.define "web" do |web|
        web.vm.box="shekeriev/centos-8-minimal"
        web.vm.hostname = "web.dof"
        web.vm.network "private_network", ip: "192.168.89.100"
        web.vm.synced_folder "php", "/vagrant"
        #web.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true
        #web.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
        web.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
        end
        config.vm.provision "shell", path: "setup.sh"
    end
    config.vm.define "db" do |db|
        db.vm.box="shekeriev/centos-8-minimal"
        db.vm.hostname = "db.dof"
        db.vm.network "private_network", ip: "192.168.89.101"
        db.vm.synced_folder "mysql", "/vagrant"
        db.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
        end
        config.vm.provision "shell", path: "setup.sh"
    end
end