---
- hosts: localhost
  connection: local

  - name: Add Docker's GPG key
    apt_key:
      id: "{{ docker_apt_key_id }}"
      url: "{{ docker_apt_key_server }}"
      state: present
    register: add_repository_key
    ignore_errors: "{{ docker_apt_ignore_key_error }}"
    tags:
      - docker

  - name: Install docker dependencies
    apt:
      name: "{{ docker__package_dependencies }}"
    tags:
      - docker

  - name: Add Docker repository.
    apt_repository:
      repo: "{{ docker_apt_repository }}"
      state: present
      update_cache: true
    tags:
      - docker

  - name: Install Docker.
    package:
      name: "{{ docker_package }}"
      state: "{{ docker_package_state }}"
    notify: restart docker
    tags:
      - docker

  - name: Check Docker service is started and enabled at boot.
    service:
      name: docker
      state: "{{ docker_service_state }}"
      enabled: "{{ docker_service_enabled }}"
    tags:
      - docker
