Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.box = "shekeriev/centos-8-minimal"
  config.vm.hostname = "ansible-homework"

  config.vm.define "ans" do |ans|
    ans.vm.network :private_network, ip: "192.168.99.100"
  end
  
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.network :private_network, ip: "192.168.99.101"
  end

  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.network :private_network, ip: "192.168.99.102"
  end


#  config.vm.synced_folder "./data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "1024"
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbook.yml"
  end
end
